### PR TITLE
apm-logo-padding-removal

### PR DESCRIPTION
**Pull request by justfinish**
Updated all of the online type logos to padding-less version according to Christian's requirement.

### CODE REVIEW

**Comment by chrhicks** [comment]
@ctumolosus @justfinish is this still a thing? Can you close if not?

**Comment by chrhicks** [comment]
@justfinish can you create a new PR? the directory structure has since been refactored and this change won't work anymore.

**Comment by justfinish** [comment]
Sure. Will do.

—
Lance

**Comment by cassiewallace** [comment]
@justfinish @chrhicks Is this still valid? If so, I can pick it up and fix it. Otherwise, let's close.

**Comment by ctumolosus** [comment]
This is a staled pull request. I suggest we close it.

**Pull request closed without merging**
