### PR TITLE
Add bitpay and klarna logos/icons/buttons.

### PR DESCRIPTION
**Pull request by jennymusing**
bitpay-logo-120
bitpay-logo-greyscale-120
bitpay-icon-120
bitpay-icon-greyscale-120
bitpay-button-120
bitpay-button-greyscale-120

klarna-logo-120
klarna-logo-greyscale-120
klarna-icon-120
klarna-icon-greyscale-120

### CODE REVIEW

**Comment by jennymusing** [comment]
@ctumolosus Thank you! Can you please help us upload these to our cdn whenever you get a chance? :)

**Comment by ctumolosus** [comment]
Sure.

**Comment by ctumolosus** [comment]
@jennymusing Done. 
https://flowcdn.io/util/icons/payment-methods/bitpay/120/original.png

**Comment by jennymusing** [comment]
@ctumolosus THANK YOU! lightening speed! ⚡️

**Pull request merged**
