### PR TITLE
Add contact_us href for confirmation page.

### PR DESCRIPTION
**Pull request by chrhicks**

### CODE REVIEW

**Comment by mbryzek** [comment]
lgtm

**Comment by mbryzek** [comment]
but note will also need to:

  1. add to https://github.com/flowcommerce/api-internal/blob/master/spec/content-internal.json
  2. update content app

**Comment by ctumolosus** [comment]
@mbryzek think we can work on this tomorrow?

**Comment by mbryzek** [comment]
Can you pls update the api ? I can take care of content

**Pull request merged**
