### PR TITLE
update bitpay mark according to their guideline

### PR DESCRIPTION
**Pull request by lance-at-flow**
Now it shows BitPay logo + BitCoin logo+ BitCoin Cash logo. This design also complies with their new guideline.

### CODE REVIEW

**Comment by ericluria** [comment]
Nice! Can you also set these as the `bitcoin` logos, too? I've got an open task to remove `bitcoin` in lieu of `bitpay`, but for the meantime it's still in use.

**Comment by lance-at-flow** [comment]
I don’t have the context but I suppose we wouldn't use `bitcoin` icons directly since there is always going to be a processor?

Do you want me to overwrite the files in `bitcoin` with `bitpay` assets for now?



LANCE LIU - Product Design m .917.971.1298 [tel:.917.971.1298] | www.flow.io Global Ecommerce now has Flow
On Mon, Jun 25, 2018 at 10:09 AM, Eric Luria <notifications@github.com> wrote:
Nice! Can you also set these as the bitcoin logos, too? I've got an open task to remove bitcoin in lieu of bitpay , but for the meantime it's still in use.

**Comment by ericluria** [comment]
@lance-at-flow yes, please. In addition to what's in this PR, can you overwrite the existing `bitcoin` logos?

**Comment by lance-at-flow** [comment]
@ericluria Sure. Done.

**Pull request merged**
